## Prerequisites: set `max_map_count`                                                                          ##
## In linux command line:                                                                                      ##
## - sudo sysctl -w vm.max_map_count=524288                                                                    ##
## - sudo sysctl -p                                                                                            ##
##                                                                                                             ##
## Install docker-compose plugin if not: https://docs.docker.com/compose/install/linux/                        ##
##                                                                                                             ##
## Execute commands below to install:                                                                          ##
## 1. sudo curl -L \                                                                                           ##
##    "https://github.com/docker/compose/releases/download/<VERSION>/docker-compose-$(uname -s)-$(uname -m)" \ ##
##    -o /usr/local/bin/docker-compose                                                                         ##
## 2. sudo mv /usr/local/bin/docker-compose /usr/bin/docker-compose                                            ##
## 2. sudo chmod +x /usr/bin/docker-compose                                                                    ##
## 3. docker-compose --version                                                                                 ##
##                                                                                                             ##
## Start docker compose: `docker-compose -p sonar -f sonarqube-compose.yml up -d`                              ##
## - `-p` specifies the name of project (the compose name)                                                     ##
## - `-f` specifies the name of docker compose file                                                            ##
## - `-d` means runs in detached mode                                                                          ##
##                                                                                                             ##
## For more info, please refer to                                                                              ##
## - https://hub.docker.com/_/sonarqube                                                                        ##
## - https://docs.sonarqube.org/latest/setup-and-upgrade/install-the-server/                                   ##

version: "3"

services:
  sonarqube:
    container_name: sonarqube-server
    image: sonarqube:lts-community
    restart: always
    ports:
      - "9191:9000"
      - "9192:9001"
    networks:
      - sonar
    depends_on:
      - db
    environment:
      # SonarQube will create database `sonar` automatically
      SONAR_JDBC_URL: jdbc:postgresql://postgresql-sonar:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    # Set ulimit options
    ulimits:
      nofile:
        soft: 131072
        hard: 131072
      nproc:
        soft: 8192
        hard: 8192
    # volumes:
    #   - sonarqube_data:/opt/sonarqube/data
    #   - sonarqube_extensions:/opt/sonarqube/extensions
    #   - sonarqube_logs:/opt/sonarqube/logs

  db:
    container_name: postgresql-sonar
    image: postgres:latest
    restart: always
    ports:
      - "9193:5432"
    networks:
      - sonar
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      # allow all IP address to connect
      # ALLOW_IP_RANGE: 0.0.0.0/0
    # volumes:
    #   - postgresql:/var/lib/postgresql
    #   - postgresql_data:/var/lib/postgresql/data

networks:
  sonar:
    driver: bridge

# volumes:
#   sonarqube_data:
#   sonarqube_extensions:
#   sonarqube_logs:
#   postgresql:
#   postgresql_data: