# Run docker-compose -p sonarqube -f sonarqube-compose.yml up -d
# -p specifies the name of project (the compose name)
# -f specifies the name of docker compose file

version: '3'
services:
  sonarqube:
    container_name: sonarqube-server
    image: sonarqube:lts-community
    ports:
      - "9191:9000"
      - "9192:9001"
    networks:
      - sonarqube-env
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresql-sonar:5432/sonar
    # restart: always
    depends_on:
      - db

  db:
    container_name: postgresql-sonar
    image: postgres
    ports:
      - "9193:5432"
    networks:
      - sonarqube-env
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    # restart: always

networks:
  sonarqube-env: