spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://192.168.101.65:3305/xc_edu_media?serverTimezone=UTC&userUnicode=true&useSSL=false
    url: jdbc:mysql://localhost:3305/xc_edu_media?serverTimezone=UTC&userUnicode=true&useSSL=false
    username: root
    # password: mysql
    password: root
  cloud:
    config:
      # 配置文件本地最优先
      override-none: true
  servlet:
    multipart:
      # 设置上传文件的大小限制 (默认为 1MB)
      max-file-size: 500MB
      max-request-size: 500MB

minio:
  # minio api 访问路径
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket:
    files: mediafiles
    videofiles: video

xxl:
  job:
    admin: 
      addresses: http://192.168.101.65:8088/xxl-job-admin
    executor:
      appname: media-process-service
      address: 
      ip: 
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
    accessToken: default_token

videoprocess:
  # ffmepeg.exe 本地路径
  ffmpegpath: D:/Program/ffmpeg/bin/ffmpeg.exe