### 查询文件信息

POST {{media_host}}/media/files?pageNo=1&pageSize=2
Content-Type: application/json

{
    "auditStatus": "",
    "fileType": "",
    "filename": ""
}


### 上传文件 (非视频)

# 返回值是 FileResultDto 对象的 JSON 信息

POST {{media_host}}/media/upload/coursefile
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="filedata"; filename="media-test.txt"
Content-Type: application/octet-stream

< D:/Download/media-test.txt
--WebAppBoundary


### 删除文件 (非视频)

# 请求参数是 FileParamDto 对象的 JSON 信息
# 返回值是 FileResultDto 对象的 JSON 信息

POST {{media_host}}/media/delete/coursefile
Content-Type: application/json

{
  "filename": "media-testd3e75fff0d5d1780eadab1cbf01b965a.txt",
  "fileType": "001003",
  "fileSize": 903,
  "tags": null,
  "username": null,
  "changeDate": null,
  "remark": null
}


### 上传文件前，检查文件是否已存在

POST {{media_host}}/media/upload/checkfile?fileMd5=40afb8ec563d4978b98da9222ccb1970


### 上传分块文件前，检查文件是否已存在

POST {{media_host}}/media/upload/checkchunk?fileMd5=40afb8ec563d4978b98da9222ccb1970&chunk=0


### 上传分块文件

POST {{media_host}}/media/upload/uploadchunk?fileMd5=40afb8ec563d4978b98da9222ccb1970&chunk=0
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="0"
Content-Type: application/octet-stream

< D:/Download/Video/chunk/0
--WebAppBoundary


### 合并分块文件

POST {{media_host}}/media/upload/mergechunks?fileMd5=40afb8ec563d4978b98da9222ccb1970&filename=test.mp4&chunkTotal=2