### 查询所有数据字典

## 响应结果示例
#[
#  {
#    "id": 12,
#    "name": "公共属性类型",
#    "code": "000",
#    "itemValues": "[{\"code\":\"1\",\"codeInt\":1,\"desc\":\"使用态\"},{\"code\":\"0\",\"codeInt\":0,\"desc\":\"删除态\"},{\"code\":\"-1\",\"codeInt\":-1,\"desc\":\"暂时态\"}]"
#  },
#  {
#    "id": 13,
#    "name": "对象的审核状态",
#    "code": "002",
#    "itemValues": "[{\"code\":\"002001\",\"desc\":\"审核未通过\"},{\"code\":\"002002\",\"desc\":\"未审核\"},{\"code\":\"002003\",\"desc\":\"审核通过\"}]"
#  }
#]

GET {{system_host}}/system/dictionary/all

### 根据码查询对应的映射名称

## 响应结果示例
#{
#  "id": 13,
#  "name": "对象的审核状态",
#  "code": "002",
#  "itemValues": "[{\"code\":\"002001\",\"desc\":\"审核未通过\"},{\"code\":\"002002\",\"desc\":\"未审核\"},{\"code\":\"002003\",\"desc\":\"审核通过\"}]"
#}

GET {{system_host}}/system/dictionary/code/002